const ASSETS = {
    'CANADIAN DOLLAR - CHICAGO MERCANTILE EXCHANGE':'cad',
    'AUSTRALIAN DOLLAR - CHICAGO MERCANTILE EXCHANGE':'aud',
    'NEW ZEALAND DOLLAR - CHICAGO MERCANTILE EXCHANGE':'nzd',
    'NZ DOLLAR - CHICAGO MERCANTILE EXCHANGE':'nzd',
    'U.S. DOLLAR INDEX - ICE FUTURES U.S.':'usd',
    'USD INDEX - ICE FUTURES U.S.':'usd',
    'EURO FX - CHICAGO MERCANTILE EXCHANGE':'eur',
    'JAPANESE YEN - CHICAGO MERCANTILE EXCHANGE':'jpy',
    'SWISS FRANC - CHICAGO MERCANTILE EXCHANGE':'chf',
    'BRITISH POUND STERLING - CHICAGO MERCANTILE EXCHANGE':'gbp',
    'BRITISH POUND - CHICAGO MERCANTILE EXCHANGE':'gbp',
}


const PREFIX_DOWNLOADABLE_FILE_NAME = 'fut_fin_xls_'

const SPECIFIC_KEYWORD = {
    LONG:'long',
    SHORT:'short',
    MAX:"max",
    MIN:"min"
}

module.exports = {
    ASSETS,
    PREFIX_DOWNLOADABLE_FILE_NAME,
    SPECIFIC_KEYWORD
}