const ASSETS = {
    'CANADIAN DOLLAR - CHICAGO MERCANTILE EXCHANGE':'cad',
    'AUSTRALIAN DOLLAR - CHICAGO MERCANTILE EXCHANGE':'aud',
    'NEW ZEALAND DOLLAR - CHICAGO MERCANTILE EXCHANGE':'nzd',
    'U.S. DOLLAR INDEX - ICE FUTURES U.S.':'usd',
    'EURO FX - CHICAGO MERCANTILE EXCHANGE':'eur',
    'JAPANESE YEN - CHICAGO MERCANTILE EXCHANGE':'jpy',
    'SWISS FRANC - CHICAGO MERCANTILE EXCHANGE':'chf',
    'BRITISH POUND STERLING - CHICAGO MERCANTILE EXCHANGE':'gbp'
}

module.exports = {
    ASSETS
}